version: '3.7'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: "Admin@123"
      POSTGRES_USER: admin
      POSTGRES_DB: pacom
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: ./server
    restart: unless-stopped
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
