name: Build next.js
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn
      - run: yarn lint
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create project.json
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_STAGING_PROJECT_ID: ${{ secrets.VERCEL_STAGING_PROJECT_ID }}
        run: |
          mkdir .vercel
          touch .vercel/project.json
          tee -a .vercel/project.json <<EOF
          {
            "orgId": "${VERCEL_ORG_ID}",
            "projectId": "${VERCEL_STAGING_PROJECT_ID}",
          }
          EOF
          cat .vercel/project.json
      - name: Deploy to staging
        run: |
          vercel -t $VERCEL_TOKEN